### ISSUE TITLE
Автоматизации

### ISSUE THREAD

**Issue by ozhigov** [apriakhin/shadowsocks-client#1]
Приветствую! Хотелось бы иметь возможность включать VPN через приложение "команды" (например, при входе в определенные приложения)

**Comment by apriakhin** [comment]
Приветствую, данная возможность есть. 
Вот инструкция https://youtube.com/shorts/n5yrC3T8KRE?si=nSmwxCvE3708rLvP

**Comment by ozhigov** [comment]
> Приветствую, данная возможность есть. 
> Вот инструкция https://youtube.com/shorts/n5yrC3T8KRE?si=nSmwxCvE3708rLvP

Виноват, почему-то когда я смотрел в приложении "Команды" не было Вашего приложения, а потом появилось. Тогда сразу дополнительный вопросик, чтобы не делать кучу постов:

Возможно ли доработать приложение так, чтобы в нем уже был предустановлен сервер или несколько серверов?

**Comment by apriakhin** [comment]
Да конечно, при старте приложения добавить условие если нету сохраненных серверов, добавить принудительно нужные сервера в SwiftData
