### ISSUE TITLE
Hope to support custom shadowsocks core

### ISSUE THREAD

**Issue by Chillln** [apriakhin/shadowsocks-client#2]
## Summary
Brief explanation of the feature.

Hope to support custom shadowsocks core.

### Basic example
Include a basic example or links here.

I see that the shadowsocks core of this project is based on [https://github.com/Jigsaw-Code/outline-go-tun2socks/](https://github.com/Jigsaw-Code/outline-go-tun2socks/)

The shadowsocks core calls [github.com/shadowsocks/go-shadowsocks2](github.com/shadowsocks/go-shadowsocks2)

### Motivation
Why are we doing this? What use cases does it support? What is the expected outcome?

Because I customized the salt encrypted by shadowsocks, the client and server failed to connect. I hope to customize the shadowsocks core

The main modifications to the shadowsocks core are:

[https://github.com/shadowsocks/go-shadowsocks2/blob/43c8294ee97d6b14c45c008f7fb37f4963a565ed/shadowaead/cipher.go#L52](https://github.com/shadowsocks/go-shadowsocks2/blob/43c8294ee97d6b14c45c008f7fb37f4963a565ed/shadowaead/cipher.go#L52)

```go
func (a *metaCipher) Encrypter(salt []byte) (cipher.AEAD, error) {
	subkey := make([]byte, a.KeySize())
	hkdfSHA1(a.psk, salt, []byte("ss-subkey"), subkey)
	return a.makeAEAD(subkey)
}
func (a *metaCipher) Decrypter(salt []byte) (cipher.AEAD, error) {
	subkey := make([]byte, a.KeySize())
	hkdfSHA1(a.psk, salt, []byte("ss-subkey"), subkey)
	return a.makeAEAD(subkey)
}
```

I hope I can replace the value of `ss-subkey` or directly download the compiled custom core.

Since I don't have an Apple developer account and Mac device at the moment, I hope you can meet my needs for customizing the shadowsocks core. Thank you very much~

**Comment by apriakhin** [comment]
Hello! Can you create a server for testing and send it to my email apriakhin@aol.com?

**Comment by Chillln** [comment]
> Hello! Can you create a server for testing and send it to my email [apriakhin@aol.com](mailto:apriakhin@aol.com)?

Sure, I have sent it to your email, please check it.

**Comment by apriakhin** [comment]
I tried changing the `"ss-subkey"` and recompiled tun2socks, but unfortunately it didn't work. 

I did a reserch, and as I realised this argument doesn't affect anything, because isn't  the salt.

https://pkg.go.dev/golang.org/x/crypto/hkdf#New 

```
// Non-secret context info, optional (can be nil).
info := []byte("hkdf example")
```

[3.2](https://www.rfc-editor.org/rfc/rfc5869.html#section-3.2).  The 'info' Input to HKDF

>    While the 'info' value is optional in the definition of HKDF, it is
>    often of great importance in applications.  Its main objective is to
>    bind the derived key material to application- and context-specific
>    information.  For example, 'info' may contain a protocol number,
>    algorithm identifiers, user identities, etc.  In particular, it may
>    prevent the derivation of the same keying material for different
>    contexts (when the same input key material (IKM) is used in such
>    different contexts).  It may also accommodate additional inputs to
>    the key expansion part, if so desired (e.g., an application may want
>    to bind the key material to its length L, thus making L part of the
>    'info' field).  There is one technical requirement from 'info': it
>    should be independent of the input key material value IKM.

Maybe you should try changing the backend to `"ss-subkey"` and see if it will connect.

**Comment by Chillln** [comment]
> I tried changing the `"ss-subkey"` and recompiled tun2socks, but unfortunately it didn't work.
> 
> I did a reserch, and as I realised this argument doesn't affect anything, because isn't the salt.
> 
> https://pkg.go.dev/golang.org/x/crypto/hkdf#New
> 
> ```
> // Non-secret context info, optional (can be nil).
> info := []byte("hkdf example")
> ```
> 
> [3.2](https://www.rfc-editor.org/rfc/rfc5869.html#section-3.2). The 'info' Input to HKDF
> 
> > While the 'info' value is optional in the definition of HKDF, it is
> > often of great importance in applications.  Its main objective is to
> > bind the derived key material to application- and context-specific
> > information.  For example, 'info' may contain a protocol number,
> > algorithm identifiers, user identities, etc.  In particular, it may
> > prevent the derivation of the same keying material for different
> > contexts (when the same input key material (IKM) is used in such
> > different contexts).  It may also accommodate additional inputs to
> > the key expansion part, if so desired (e.g., an application may want
> > to bind the key material to its length L, thus making L part of the
> > 'info' field).  There is one technical requirement from 'info': it
> > should be independent of the input key material value IKM.
> 
> Maybe you should try changing the backend to `"ss-subkey"` and see if it will connect.

Ok, thank you very much, I'll do that.
